{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: user
              app.kubernetes.io/instance: {{ .Release.Name }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: stock
              app.kubernetes.io/instance: {{ .Release.Name }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: trading
              app.kubernetes.io/instance: {{ .Release.Name }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: portfolio
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.mongodb.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-backend-egress
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - user
          - stock
          - trading
          - portfolio
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mongodb
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.mongodb.port }}
    - to:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.dns.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.dns.podSelector | nindent 12 }}
      ports:
        - protocol: UDP
          port: {{ .Values.networkPolicy.dns.port }}
        - protocol: TCP
          port: {{ .Values.networkPolicy.dns.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-backend-ingress
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - user
          - stock
          - trading
          - portfolio
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: nginx-gateway
              app.kubernetes.io/instance: {{ .Release.Name }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: frontend
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: {{ .Values.user.service.port }}
        - protocol: TCP
          port: {{ .Values.stock.service.port }}
        - protocol: TCP
          port: {{ .Values.trading.service.port }}
        - protocol: TCP
          port: {{ .Values.portfolio.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-gateway-egress
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: frontend
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.service.port }}
    - to:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - user
                  - stock
                  - trading
                  - portfolio
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: {{ .Values.user.service.port }}
        - protocol: TCP
          port: {{ .Values.stock.service.port }}
        - protocol: TCP
          port: {{ .Values.trading.service.port }}
        - protocol: TCP
          port: {{ .Values.portfolio.service.port }}
    - to:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.dns.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.dns.podSelector | nindent 12 }}
      ports:
        - protocol: UDP
          port: {{ .Values.networkPolicy.dns.port }}
        - protocol: TCP
          port: {{ .Values.networkPolicy.dns.port }}
{{- end }}
